/**
 * N4-SD-IMPLEMENTATION conformance. Expected bytes and digests are literal published
 * E01–E14 fixtures, never generated by the implementation under test. P0/P1 fixtures
 * use governance's explicit illustrative binding assumption, not registered populations.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { TextDecoder } from 'node:util';
import {
  ScreenDefinition,
  ScreenDefinitionError,
  type ScreenDefinitionErrorCode,
  type ScreeningPredicate,
} from '../../src/sector-engines/cross-sector/definition/ScreenDefinition';
import { ScreenDefinition as BarrelScreenDefinition } from '../../src/sector-engines/cross-sector';
import {
  ScreeningPopulationGuard,
  type ScreeningPopulation,
} from '../../src/sector-engines/cross-sector/population/ScreeningPopulation';
import fixtures from './fixtures/np12-n4-screen-definition-format1.json';

const P0 = '0'.repeat(64);
const P1 = `${'0'.repeat(63)}1`;
const assumedP0Binding = { identity: P0 };
const predicate = (operand: string, field: ScreeningPredicate['field'] = 'growth',
  operator: ScreeningPredicate['operator'] = 'eq'): ScreeningPredicate => ({ field, operator, operand });
const input = (overrides: Record<string, unknown> = {}) => ({
  definitionId: 'd', version: '1', populationIdentity: P0, predicates: [], ...overrides,
});
const create = (overrides: Record<string, unknown> = {}) => ScreenDefinition.create(input(overrides), assumedP0Binding);

function semantics(definition: ScreenDefinition) {
  return {
    definitionId: definition.definitionId,
    version: definition.version,
    populationIdentity: definition.populationIdentity,
    predicates: definition.predicates,
  };
}

function rejected(value: unknown, code: ScreenDefinitionErrorCode, ...bindings: unknown[]): void {
  const binding = bindings.length === 0 ? assumedP0Binding : bindings[0];
  assert.throws(
    () => ScreenDefinition.create(value, binding as Pick<ScreeningPopulation, 'identity'>),
    (error: unknown) => error instanceof ScreenDefinitionError && error.code === code,
  );
}

/** Independent test-only framing inspection: strict UTF-8, U32BE, and exact message end. */
function inspectFrames(bytes: Buffer) {
  assert.equal(bytes.subarray(0, 9).toString('hex'), '4e5031324445460001');
  let offset = 9;
  const u32 = () => {
    assert.ok(offset + 4 <= bytes.length);
    const n = bytes.readUInt32BE(offset);
    offset += 4;
    return n;
  };
  const text = () => {
    const length = u32();
    assert.ok(offset + length <= bytes.length);
    const value = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true })
      .decode(bytes.subarray(offset, offset + length));
    offset += length;
    return value;
  };
  const definitionId = text();
  const version = text();
  const populationIdentity = text();
  const count = u32();
  const predicates = [];
  for (let i = 0; i < count; i++) predicates.push({ field: text(), operator: text(), operand: text() });
  assert.equal(offset, bytes.length, 'no terminator, newline, padding, second message, or other trailer');
  return { definitionId, version, populationIdentity, predicates, count };
}

test('N4: E01–E14 literal fixtures match the unchanged authoritative grammar blob', () => {
  assert.equal(fixtures.sourceBlob, '6d823aeecc2a6047782f48dad33d61f26bbe89d8');
  const source = readFileSync(resolve(__dirname, '../../../', fixtures.source));
  assert.equal(createHash('sha1').update(`blob ${source.length}\0`).update(source).digest('hex'), fixtures.sourceBlob);
  assert.deepEqual(fixtures.examples.map((entry) => entry.example),
    Array.from({ length: 14 }, (_, i) => `E${String(i + 1).padStart(2, '0')}`));
  for (const fixture of fixtures.examples) {
    const section = source.toString('utf8').split(`### ${fixture.example} — `)[1]
      .split(/\n### E|\n## 12\./)[0];
    const hexBlocks = [...section.matchAll(/```text\n([0-9a-f\n]+)\n```/g)];
    assert.equal(hexBlocks.length, 1);
    assert.equal(hexBlocks[0][1].replace(/\n/g, ''), fixture.preimageHex);
    assert.ok(section.includes(`\`${fixture.sha256}\``));
    assert.equal(createHash('sha256').update(Buffer.from(fixture.preimageHex, 'hex')).digest('hex'), fixture.sha256);
  }
});

for (const fixture of fixtures.examples) {
  test(`N4 ${fixture.example}: ${fixture.title} — canonical semantics, exact published bytes and SHA-256`, () => {
    for (const variant of fixture.inputs) {
      // This mock is ONLY the independently bound reference assumption expressly made in §11.
      const definition = ScreenDefinition.create(variant, { identity: variant.populationIdentity });
      assert.deepEqual(semantics(definition), fixture.canonical);
      const bytes = definition.canonicalBytes();
      assert.deepEqual(bytes, Buffer.from(fixture.preimageHex, 'hex'));
      assert.equal(bytes.length, fixture.octets);
      assert.equal(definition.sha256(), fixture.sha256);
      assert.match(definition.sha256(), /^[0-9a-f]{64}$/);
      const { count, ...parsed } = inspectFrames(bytes);
      assert.equal(count, fixture.canonical.predicates.length);
      assert.deepEqual(parsed, fixture.canonical);
    }
  });
}

test('N4: the existing cross-sector barrel exports the isolated runtime type', () => {
  assert.equal(BarrelScreenDefinition, ScreenDefinition);
});

test('N4: both opaque identifiers distinguish exact case, numeric-looking and semver-looking text', () => {
  for (const field of ['definitionId', 'version']) {
    const spellings = ['ABC', 'abc', '1', '01', '1.0', '1.0.0', 'v1', 'V1', ' d ', 'd', 'd d', 'd  d', 'é', 'e\u0301'];
    const definitions = spellings.map((spelling) => create({ [field]: spelling }));
    assert.equal(new Set(definitions.map((definition) => definition.canonicalBytes().toString('hex'))).size, spellings.length);
    definitions.forEach((definition, i) => assert.equal(semantics(definition)[field as 'definitionId' | 'version'], spellings[i]));
  }
});

test('N4: both identifiers reject non-text without invoking coercion, aliases or defaults', () => {
  const noCoercion = { toString: () => { throw new Error('coercion must not be invoked'); } };
  for (const field of ['definitionId', 'version']) {
    for (const invalid of [undefined, null, 1, 0, -0, NaN, Infinity, true, 1n, Symbol('d'),
      {}, [], ['d'], new String('d'), noCoercion, Buffer.from([0xc0, 0xaf])]) {
      rejected(input({ [field]: invalid }), 'INVALID_IDENTIFIER');
    }
  }
});

const whitespaceScalars = [
  0x0009, 0x000a, 0x000b, 0x000c, 0x000d, 0x0020, 0x0085, 0x00a0, 0x1680,
  ...Array.from({ length: 11 }, (_, i) => 0x2000 + i), 0x2028, 0x2029, 0x202f, 0x205f, 0x3000,
];

test('N4: exact frozen White_Space set rejects blank identifiers but is preserved around non-blank text', () => {
  for (const field of ['definitionId', 'version']) {
    for (const blank of ['', ...whitespaceScalars.map((scalar) => String.fromCodePoint(scalar)),
      String.fromCodePoint(...whitespaceScalars)]) {
      rejected(input({ [field]: blank }), 'INVALID_IDENTIFIER');
      if (blank) {
        const admitted = `${blank}x${blank}`;
        const definition = create({ [field]: admitted });
        assert.equal(semantics(definition)[field as 'definitionId' | 'version'], admitted);
        assert.equal(inspectFrames(definition.canonicalBytes())[field as 'definitionId' | 'version'], admitted);
      }
    }
  }
});

test('N4: literal BOM, NUL, controls, noncharacters, unassigned and supplementary scalars remain data', () => {
  const values = ['\ufeff', '\u0000', '\u0001', '\u180e', '\u200b', '\u0378', '\ufffe', '\uffff', '\ufffd',
    '\u007f', '\u0080', '\u07ff', '\u0800', '\ud7ff', '\ue000', '\ud800\udc00', '\udbff\udfff',
    '🚀', '\ufeffx\ufeff', 'a\u0000:|"\r\nNP12DEF\u0000\u0001'];
  for (const field of ['definitionId', 'version']) {
    for (const value of values) {
      const definition = create({ [field]: value });
      assert.equal(inspectFrames(definition.canonicalBytes())[field as 'definitionId' | 'version'], value);
    }
  }
  assert.equal(create({ definitionId: '🚀' }).canonicalBytes().subarray(9, 17).toString('hex'), '00000004f09f9a80');
  assert.equal(create({ definitionId: '\ufeff' }).canonicalBytes().subarray(9, 16).toString('hex'), '00000003efbbbf');
  assert.equal(create({ definitionId: '\ufffd' }).canonicalBytes().subarray(9, 16).toString('hex'), '00000003efbfbd');
});

test('N4: unpaired UTF-16 surrogates reject before UTF-8 replacement can collapse text', () => {
  for (const field of ['definitionId', 'version']) {
    for (const invalid of ['\ud800', '\udbff', '\udc00', '\udfff', 'x\ud800', '\ud800x',
      '\ud800\ud800', '\udc00\ud800', '\ud800\udc00\udc00', '\ud800\udc00\ud800']) {
      rejected(input({ [field]: invalid }), 'INVALID_IDENTIFIER');
    }
  }
});

test('N4: identifier framing is byte-based U32BE, not UTF-16 length or naive concatenation', () => {
  const bytes = create({ definitionId: 'é'.repeat(150) }).canonicalBytes();
  assert.equal(bytes.subarray(9, 13).toString('hex'), '0000012c'); // 300 UTF-8 bytes, not 150 code units.
  assert.equal(inspectFrames(bytes).definitionId, 'é'.repeat(150));
  assert.notDeepEqual(create({ definitionId: 'a', version: 'bc' }).canonicalBytes(),
    create({ definitionId: 'ab', version: 'c' }).canonicalBytes());
});

test('N4: admitted decimal boundaries and all allowed fractional precisions canonicalize exactly', () => {
  const admitted = [
    ['0', '0'], ['0.000000', '0'], ['0.000001', '0.000001'], ['0.1', '0.1'], ['0.01', '0.01'],
    ['0.001', '0.001'], ['0.0001', '0.0001'], ['0.00001', '0.00001'], ['0.500000', '0.5'],
    ['75.0', '75'], ['75.000000', '75'], ['75.123456', '75.123456'], ['99.999999', '99.999999'],
    ['100', '100'], ['100.000000', '100'], ['10.010100', '10.0101'], ['0.100001', '0.100001'],
  ];
  for (const [source, canonical] of admitted) {
    for (const field of ['conviction', 'growth', 'quality'] as const) {
      const definition = create({ predicates: [predicate(source, field)] });
      assert.equal(definition.predicates[0].operand, canonical);
      assert.equal(inspectFrames(definition.canonicalBytes()).predicates[0].operand, canonical);
    }
  }
});

test('N4: all admitted negative-zero spellings normalize and deduplicate with positive zero', () => {
  const zeros = ['-0', '-0.0', '-0.000000', '-0.000', '0', '0.000000'];
  const expected = create({ predicates: [predicate('0')] });
  for (const source of zeros) {
    const definition = create({ predicates: [predicate(source)] });
    assert.deepEqual(definition.predicates, [predicate('0')]);
    assert.deepEqual(definition.canonicalBytes(), expected.canonicalBytes());
    assert.equal(definition.sha256(), expected.sha256());
  }
  assert.deepEqual(create({ predicates: zeros.map((zero) => predicate(zero)) }).predicates, [predicate('0')]);
});

test('N4: invalid decimal precision, syntax, range, exponent, NaN and infinities reject without rounding', () => {
  const invalid = [
    '75.1234567', '75.0000000', '0.0000000', '-0.0000000', '100.0000000', '0.0000001',
    '100.000001', '101', '-1', '-0.000001', '999', '9'.repeat(1000),
    '1e1', '1E1', '0e0', '1e-6', '1e+1', 'NaN', 'Infinity', '+Infinity', '-Infinity',
    '00', '01', '075.0', '00.5', '-00', '-00.0', '+0', '+75', '.5', '1.', '-.0', '--0',
    '', ' ', ' 75', '75 ', '75\n', '75\r\n', '7\u00005', '７５', '0,5', '1_0', '0x10',
    null, undefined, NaN, Infinity, -Infinity, 75, 75.123456, -0, true, 75n, {}, [], new String('75'),
  ];
  for (const operand of invalid) {
    rejected(input({ predicates: [{ field: 'growth', operator: 'eq', operand }] }), 'INVALID_OPERAND');
  }
});

test('N4: missing/malformed content and predicate collections never become an empty collection', () => {
  for (const value of [null, undefined, 1, 'd', [], false]) rejected(value, 'INVALID_DEFINITION');
  rejected({}, 'INVALID_IDENTIFIER');
  for (const field of ['definitionId', 'version']) {
    const value: Record<string, unknown> = input();
    delete value[field];
    rejected(value, 'INVALID_IDENTIFIER');
  }
  for (const predicates of [undefined, null, {}, '[]', 0, { and: [] }, { or: [] },
    [null], [undefined], [[]], [[predicate('1')]], [{ or: [predicate('1')] }],
    [{ not: predicate('1') }], [{ field: 'growth', operator: 'eq' }], Array(1),
    [{ ...predicate('1'), not: true }], [{ ...predicate('1'), or: [predicate('2')] }],
    [{ ...predicate('1'), predicates: [predicate('2')] }]]) {
    rejected(input({ predicates }), 'INVALID_PREDICATE');
  }
});

test('N4: only the exact three fields and five operators are admitted, without aliases', () => {
  for (const field of ['confidence', 'risk', 'valuation', 'capitalEfficiency', 'moat', 'sector', 'verdict',
    'companyId', 'raw fundamentals', 'Conviction', 'GROWTH', 'growth ', ' quality', '', 1, null]) {
    rejected(input({ predicates: [{ field, operator: 'eq', operand: '1' }] }), 'INVALID_PREDICATE');
  }
  for (const operator of ['range', 'range_inc', 'ne', 'in', 'exists', 'absent', 'not', 'and', 'or',
    'EQ', '>=', '=', 'lt ', '', 1, null]) {
    rejected(input({ predicates: [{ field: 'growth', operator, operand: '1' }] }), 'INVALID_PREDICATE');
  }
  assert.equal(create({ predicates: [] }).predicates.length, 0);
});

test('N4: complete field → operator → exact numeric ordering, independent of caller order and spelling', () => {
  const expected: ScreeningPredicate[] = [];
  for (const field of ['conviction', 'growth', 'quality'] as const) {
    for (const operator of ['eq', 'gt', 'gte', 'lt', 'lte'] as const) {
      for (const operand of ['0', '0.000001', '0.1', '0.100001', '0.100002', '2', '10', '99.999999', '100']) {
        expected.push(predicate(operand, field, operator));
      }
    }
  }
  const original = create({ predicates: expected });
  const reversed = create({ predicates: [...expected].reverse() });
  const duplicated = create({ predicates: [...expected, ...expected.map((p) => ({ ...p,
    operand: p.operand.includes('.') ? p.operand : `${p.operand}.000000` }))].reverse() });
  assert.deepEqual(original.predicates, expected);
  assert.deepEqual(reversed.predicates, expected);
  assert.deepEqual(duplicated.predicates, expected);
  assert.deepEqual(original.canonicalBytes(), reversed.canonicalBytes());
  assert.deepEqual(original.canonicalBytes(), duplicated.canonicalBytes());
  assert.equal(original.sha256(), duplicated.sha256());
});

test('N4: contradictions and non-identical redundancies remain, while only exact canonical triples collapse', () => {
  const definition = create({ predicates: [
    predicate('10'), predicate('2'), predicate('2.000000'), predicate('10', 'growth', 'gt'),
    predicate('9', 'growth', 'gt'), predicate('1', 'growth', 'lt'), predicate('2', 'quality'),
  ] });
  assert.deepEqual(definition.predicates, [predicate('2'), predicate('10'), predicate('9', 'growth', 'gt'),
    predicate('10', 'growth', 'gt'), predicate('1', 'growth', 'lt'), predicate('2', 'quality')]);
  assert.equal(inspectFrames(definition.canonicalBytes()).count, 6);
});

test('N4: deduplicated collection count uses U32BE beyond one octet and ends at the last operand', () => {
  const predicates = Array.from({ length: 300 }, (_, i) => predicate(`0.${String(i + 1).padStart(6, '0')}`));
  const definition = create({ predicates: [...predicates].reverse().concat(predicates) });
  const bytes = definition.canonicalBytes();
  assert.equal(bytes.subarray(87, 91).toString('hex'), '0000012c');
  assert.equal(inspectFrames(bytes).count, 300);
  assert.equal(bytes[bytes.length - 1], '3'.charCodeAt(0)); // canonical final operand is 0.0003.
  assert.equal(bytes.length, 91 + definition.predicates.reduce((sum, p) => sum + 12
    + Buffer.byteLength(p.field) + Buffer.byteLength(p.operator) + Buffer.byteLength(p.operand), 0));
});

test('N4: population reference needs an explicit exact binding, not just valid hex', () => {
  rejected(input({ populationIdentity: P1 }), 'INVALID_POPULATION_BINDING');
  for (const binding of [undefined, null, {}, { identity: P1 }, { identity: 0 }, { identity: P0 + '\n' }]) {
    rejected(input(), 'INVALID_POPULATION_BINDING', binding);
  }
  for (const populationIdentity of [undefined, null, 0, '', '0'.repeat(63), '0'.repeat(65),
    'g'.repeat(64), `0x${P0}`, `sha256:${P0}`, ` ${P0}`, `${P0}\n`, Buffer.from(P0, 'hex')]) {
    rejected(input({ populationIdentity }), 'INVALID_POPULATION_BINDING');
  }
  const lower = 'abcdef0123456789'.repeat(4);
  const upper = lower.toUpperCase();
  rejected(input({ populationIdentity: upper }), 'INVALID_POPULATION_BINDING', { identity: lower });
  // Hypothetical exactly verified spelling per §7, not an alias minted from the current lowercase producer.
  const definition = ScreenDefinition.create(input({ populationIdentity: upper }), { identity: upper });
  assert.equal(inspectFrames(definition.canonicalBytes()).populationIdentity, upper);
  assert.equal(definition.canonicalBytes().subarray(19, 23).toString('hex'), '00000040');
  assert.equal(definition.canonicalBytes().subarray(23, 87).toString('ascii'), upper);
});

test('N4: real G1–G5 boundary supplies the binding; values/order stay outside Definition content', () => {
  const outputs = [
    { companyId: 'H1', sector: ' technology ', composite: 70, confidence: 0.8, qualityScore: 60, riskScore: 20 },
    { companyId: 'H2', sector: 'Banking', composite: 50, confidence: 0.8, qualityScore: 60, riskScore: 20 },
  ];
  const population = ScreeningPopulationGuard.fromOutputs(outputs);
  const definition = ScreenDefinition.create(input({ populationIdentity: population.identity }), population);
  const changedValues = ScreeningPopulationGuard.fromOutputs([...outputs].reverse().map((output) => ({ ...output, composite: 1 })));
  assert.equal(population.identity, changedValues.identity);
  assert.deepEqual(ScreenDefinition.create(input({ populationIdentity: population.identity }), changedValues).canonicalBytes(),
    definition.canonicalBytes());
  const differentMembers = ScreeningPopulationGuard.fromOutputs([outputs[0]]);
  rejected(input({ populationIdentity: population.identity }), 'INVALID_POPULATION_BINDING', differentMembers);
  assert.throws(() => ScreeningPopulationGuard.fromOutputs([outputs[0], outputs[0]]));
  assert.deepEqual(Object.keys(definition), ['definitionId', 'version', 'populationIdentity', 'predicates']);
});

test('N4: metadata, property order, members, results and digest itself never enter the preimage', () => {
  const baseline = create({ predicates: [predicate('75', 'conviction', 'gte')] });
  const raw = {
    predicates: [{ operand: '75.0', operator: 'gte', field: 'conviction' }],
    populationIdentity: P0, version: '1', definitionId: 'd',
    executionId: 'exec', resultId: 'result', snapshotId: 'snapshot', evidenceId: 'evidence',
    timestamp: '2026-10-02', runtimeMetadata: { anything: true }, members: ['not content'],
    result: { holdings: 100 }, digest: 'not part of its own preimage',
  };
  Object.defineProperty(raw, 'callerMetadata', { enumerable: true, get: () => { throw new Error('must not be read'); } });
  const definition = ScreenDefinition.create(raw, assumedP0Binding);
  assert.deepEqual(semantics(definition), semantics(baseline));
  assert.deepEqual(definition.canonicalBytes(), baseline.canonicalBytes());
  assert.equal(definition.sha256(), baseline.sha256());
  assert.notEqual(create({ predicates: [predicate('76', 'conviction', 'gte')] }).sha256(), baseline.sha256());
  assert.deepEqual([definition.definitionId, definition.version], [baseline.definitionId, baseline.version],
    'content digest is not the Definition identity');
});

test('N4: canonical content is immutable and returned byte buffers cannot mutate future bytes/digests', () => {
  const rawPredicate = { field: 'growth', operator: 'eq', operand: '2.0' };
  const raw = input({ predicates: [rawPredicate] });
  const definition = ScreenDefinition.create(raw, assumedP0Binding);
  const expected = definition.canonicalBytes();
  const digest = definition.sha256();
  raw.definitionId = 'changed';
  rawPredicate.operand = '3';
  assert.ok(Object.isFrozen(definition));
  assert.ok(Object.isFrozen(definition.predicates));
  assert.ok(Object.isFrozen(definition.predicates[0]));
  assert.throws(() => Object.assign(definition, { version: 'changed' }), TypeError);
  definition.canonicalBytes().fill(0);
  assert.deepEqual(definition.canonicalBytes(), expected);
  assert.equal(definition.sha256(), digest);
});

test('N4: deterministic exact decimal round trips over 1000 scaled-integer samples', () => {
  let q = 7;
  for (let i = 0; i < 1000; i++) {
    q = (q * 48271) % 100_000_001; // Exact integer arithmetic within Number's safe range.
    const whole = Math.floor(q / 1_000_000);
    const fraction = String(q % 1_000_000).padStart(6, '0');
    const canonicalFraction = fraction.replace(/0+$/, '');
    const canonical = `${whole}${canonicalFraction ? `.${canonicalFraction}` : ''}`;
    const padded = `${whole}.${fraction}`;
    const a = create({ predicates: [predicate(padded)] });
    const b = create({ predicates: [predicate(canonical), predicate(padded)] });
    assert.deepEqual(a.predicates, [predicate(canonical)]);
    assert.deepEqual(a.canonicalBytes(), b.canonicalBytes());
    assert.equal(a.sha256(), b.sha256());
    assert.deepEqual(a.canonicalBytes(), a.canonicalBytes());
  }
});
