#!/bin/bash
IRR=/tmp/inv/irr.git; IPD=/tmp/inv/ipd.git
ok(){ echo "PASS | $1"; }; bad(){ echo "FAIL | $1"; }
exists(){ git -C "$1" cat-file -e "$2:$3" 2>/dev/null; }
echo "== S0 counts (report section 0 / G) =="
c=$(git -C $IRR rev-list --count refs/heads/main); [ "$c" = 168 ] && ok "IRR main commits = $c (report 168)" || bad "IRR main commits = $c (report 168)"
c=$(git -C $IPD rev-list --count refs/heads/main); [ "$c" = 94 ] && ok "IPD main commits = $c (report 94)" || bad "IPD main commits = $c (report 94)"
c=$(git -C $IRR for-each-ref --format='%(objectname)' refs/heads refs/pull refs/tags | while read x; do git -C $IRR rev-parse "$x^{tree}"; done | sort -u | wc -l); [ "$c" = 72 ] && ok "IRR unique trees = $c (report 72)" || bad "IRR unique trees = $c (report 72)"
c=$(git -C $IPD for-each-ref --format='%(objectname)' refs/heads refs/pull refs/tags | while read x; do git -C $IPD rev-parse "$x^{tree}"; done | sort -u | wc -l); [ "$c" = 33 ] && ok "IPD unique trees = $c (report 33)" || bad "IPD unique trees = $c (report 33)"
m=0; u=0; for h in $(git -C $IRR for-each-ref --format='%(refname)' refs/heads); do if git -C $IRR merge-base --is-ancestor $h refs/heads/main 2>/dev/null; then m=$((m+1)); else u=$((u+1)); fi; done; [ "$m/$u" = "51/19" ] && ok "IRR heads merged/unmerged = $m/$u (report 51/19)" || bad "IRR heads merged/unmerged = $m/$u (report 51/19)"
m=0; u=0; for h in $(git -C $IPD for-each-ref --format='%(refname)' refs/heads); do if git -C $IPD merge-base --is-ancestor $h refs/heads/main 2>/dev/null; then m=$((m+1)); else u=$((u+1)); fi; done; [ "$m/$u" = "7/25" ] && ok "IPD heads merged/unmerged = $m/$u (report 7/25)" || bad "IPD heads merged/unmerged = $m/$u (report 7/25)"
for pair in "phase13-next:78" "gai-impl-canonical:47" "arena/01a0ddea-iips-review-recovered:102" "arena/01a0e30f-iips-review-recovered:103" "arena/01a0f1b3-iips-review-recovered:28"; do b=${pair%%:*}; e=${pair##*:}; a=$(git -C $IRR rev-list --count refs/heads/main..refs/heads/$b 2>/dev/null); [ "$a" = "$e" ] && ok "IRR $b ahead of main = $a (report $e)" || bad "IRR $b ahead of main = $a (report $e)"; done
echo "PR states (raw json): IRR=$(python3 -c "import json;d=json.load(open('/home/user/lineage-investigation-2026-10-08/raw/irr_prs.json'));print(len(d), sorted(set(x.get('state') for x in d)), sorted(set(x.get('mergedAt') is not None for x in d)))" 2>/dev/null) IPD=$(python3 -c "import json;d=json.load(open('/home/user/lineage-investigation-2026-10-08/raw/ipd_prs.json'));print(len(d), sorted(set(x.get('state') for x in d)), sorted(set(x.get('mergedAt') is not None for x in d)))" 2>/dev/null)"
echo "== S1 pickaxe counts (report G) =="
for t in "Command Center:0:0" "Decision Center:0:14" "Company Workspace:0:15" "Replay Studio:0:14" "Research Hub:2:23" "Widget:2:7" "D107:0:8" "AG-5:3:2" "features/reports:7:4"; do term=${t%%:*}; rest=${t#*:}; er=${rest%%:*}; ei=${rest##*:}; nr=$(git -C $IRR log --all -i -G"$term" --oneline 2>/dev/null | wc -l); ni=$(git -C $IPD log --all -i -G"$term" --oneline 2>/dev/null | wc -l); [ "$nr" = "$er" ] && [ "$ni" = "$ei" ] && ok "pickaxe '$term' IRR=$nr (report $er) IPD=$ni (report $ei)" || bad "pickaxe '$term' IRR=$nr (report $er) IPD=$ni (report $ei)"; done
echo "== S2 absence on IRR main (report says absent / not on M) =="
for p in frontend/src/features/shell/CommandPalette.tsx frontend/src/features/intelligence/IntelligenceOpportunities.tsx frontend/src/features/intelligence/IntelligenceRisks.tsx frontend/src/features/intelligence/IntelligenceRankings.tsx frontend/src/features/research/ResearchHub.tsx frontend/src/features/research/SectorIntelligence.tsx frontend/src/features/notes/NotesDrawer.tsx frontend/src/features/notifications/NotificationDrawer.tsx frontend/server/notes/notes-service.ts frontend/server/notifications/notification-service.ts frontend/src/features/workflow/WorkflowView.tsx frontend/src/features/reports/Reports.tsx frontend/src/api/reports.ts frontend/server/directory/roster-directory.ts frontend/server/directory/idp-sync.ts frontend/server/reports/reports-service.ts; do exists $IRR refs/heads/main $p && bad "PRESENT on IRR main: $p (report: absent)" || ok "absent on IRR main: $p"; done
echo "== S3 presence on IRR main (report says on M) =="
for p in frontend/server/d115-runtime.ts frontend/server/tenant-membership-store.ts frontend/server/user-portfolio/translationBoundary.ts frontend/server/reports/persistence-port.ts iips-platform/src/sector-engines/cross-sector/opportunity/OpportunityEngine.ts iips-platform/src/sector-engines/cross-sector/ranking/RankingEngine.ts iips-platform/src/sector-engines/cross-sector/portfolio/PortfolioIntelligence.ts iips-platform/src/snapshot/SnapshotStore.ts iips-platform/src/snapshot/SnapshotService.ts iips-platform/src/replay/ReplayService.ts iips-platform/src/distributed/WorkflowRuntime.ts frontend/src/features/research/MacroContext.tsx frontend/src/features/research/CompanyIntelligence.tsx frontend/src/features/company/CompanyIntelligence.tsx frontend/src/features/replay/ReplayExplorer.tsx frontend/src/features/intelligence/DecisionMatrix.tsx docs/v3.0/navigation-model.md evidence/integration/convergence/2026-10-07/P5-capability-sweep.md docs/integration/IDENTITY-TENANT-DOMAIN-SCOPE-DECISION.md; do exists $IRR refs/heads/main $p && ok "present on IRR main: $p" || bad "ABSENT on IRR main: $p (report: present)"; done
echo "== S4 IRR main App.tsx route lines (report L50, L52, L57, L59, L60, L61) =="
git -C $IRR show refs/heads/main:frontend/src/app/App.tsx | grep -n 'path=' | sed -n '1,80p' | grep -E 'research|intelligence|evidence|workflow|reports|executive|admin' | cut -c1-150
echo "== S5 IRR main: 'Command palette' text only in docs (report: M navigation model requires it) =="
git -C $IRR grep -n -i 'command palette' refs/heads/main -- docs | cut -c1-160 | head -5
echo "== S6 IPD main absence (report says absent on IPD M) =="
for p in frontend/src/features/reports/Reports.tsx frontend/src/features/research/SectorIntelligence.tsx frontend/src/features/company/CompanyIntelligence.tsx frontend/src/features/executive/ExecutiveDashboard.tsx frontend/server/market-data/eod-pipeline.ts frontend/server/research-sector-transport.ts docs/D107_EOD_PRODUCTION_READINESS_GATE_ADJUDICATION.md src/identity/mapping_store.ts src/app_identity/service.ts; do exists $IPD refs/heads/main $p && bad "PRESENT on IPD main: $p" || ok "absent on IPD main: $p"; done
echo "== S7 IPD main presence (report says present on IPD M) =="
for p in src/identity/mapping_store.ts src/ui/view_models/ui01_replay_studio.ts src/operations/slo_evaluator.ts src/quality/freshness_evaluator.ts frontend/src/features/portfolio/BrokerImportModal.tsx evidence/bi07/bi07-final-certification.json; do exists $IPD refs/heads/main $p && ok "present on IPD main: $p" || bad "ABSENT on IPD main: $p"; done
echo "== S8 Phase 14.1 archive: size and entry count (report 719,726 B; 1,128 entries) =="
b=$(git -C $IRR cat-file -s refs/heads/phase14.1-recovery-deposit:artifacts/phase14.1-recovery-snapshot/v3.0-phase14.1-certified-snapshot.tar.gz 2>/dev/null); e=$(git -C $IRR show refs/heads/phase14.1-recovery-deposit:artifacts/phase14.1-recovery-snapshot/v3.0-phase14.1-certified-snapshot.tar.gz | tar -tzf - | wc -l); [ "$b" = 719726 ] && ok "archive bytes = $b" || bad "archive bytes = $b (report 719726)"; [ "$e" = 1128 ] && ok "archive entries = $e" || bad "archive entries = $e (report 1128)"
echo "WorkflowView tracked (non-archive) on phase14.1-recovery-deposit: $(git -C $IRR ls-tree -r --name-only refs/heads/phase14.1-recovery-deposit | grep -c WorkflowView)"
echo "== S9 reports-transport blob equality main vs branch arena/01a0f1b3 =="
m=$(git -C $IRR rev-parse refs/heads/main:frontend/server/reports-transport.ts); bb=$(git -C $IRR rev-parse refs/heads/arena/01a0f1b3-iips-review-recovered:frontend/server/reports-transport.ts); echo "main blob=$m branch blob=$bb"; [ "$m" = "$bb" ] && echo "SAME blob" || echo "DIFFERENT blob"; git -C $IRR merge-base --is-ancestor refs/heads/arena/01a0f1b3-iips-review-recovered refs/heads/main && echo "arena/01a0f1b3 tip IS ancestor of main" || echo "arena/01a0f1b3 tip NOT ancestor of main"
