#!/bin/bash
# Validation pass for the lineage investigation record (read-only; scratch mirrors refreshed 2026-10-08).
IRR=/tmp/inv/irr.git; IPD=/tmp/inv/ipd.git
pass(){ echo "[PASS] $1"; }; fail(){ echo "[FAIL] $1"; }
chk(){ if eval "$2"; then pass "$1"; else fail "$1"; fi; }
echo "== V1-V2 authoritative baselines =="
echo "V1 IRR origin/main = $(git -C $IRR rev-parse refs/heads/main) tree=$(git -C $IRR rev-parse refs/heads/main^{tree})"
echo "V2 IPD origin/main = $(git -C $IPD rev-parse refs/heads/main) tree=$(git -C $IPD rev-parse refs/heads/main^{tree})"
echo "== V3-V4 'Command Center' exact phrase across all unique trees =="
hits=0; for t in $(git -C $IRR for-each-ref --format='%(objectname)' refs/heads refs/pull refs/tags | while read c; do git -C $IRR rev-parse "$c^{tree}" 2>/dev/null; done | sort -u); do n=$(git -C $IRR grep -l -i -E 'command[ -]?cent(er|re)' $t -- ':!*.png' 2>/dev/null | wc -l); hits=$((hits+n)); done; echo "V3 IRR Command Center text hits (all trees): $hits"
hits=0; for t in $(git -C $IPD for-each-ref --format='%(objectname)' refs/heads refs/pull refs/tags | while read c; do git -C $IPD rev-parse "$c^{tree}" 2>/dev/null; done | sort -u); do n=$(git -C $IPD grep -l -i -E 'command[ -]?cent(er|re)' $t -- ':!*.png' 2>/dev/null | wc -l); hits=$((hits+n)); done; echo "V4 IPD Command Center text hits (all trees): $hits"
echo "== V5-V6 D-2 and P3 statements on IRR origin/main =="
git -C $IRR show refs/heads/main:docs/integration/IDENTITY-TENANT-DOMAIN-SCOPE-DECISION.md | grep -c 'NO GOVERNED CROSS-REPO IDENTITY MAPPING ESTABLISHED' | sed 's/^/V5 D-2 "NO GOVERNED CROSS-REPO IDENTITY MAPPING ESTABLISHED" lines: /'
git -C $IRR show refs/heads/main:docs/integration/IDENTITY-TENANT-DOMAIN-SCOPE-DECISION.md | grep -c 'NO UNIVERSAL TENANT AUTHORITY\|NO GOVERNED COMPANY IDENTITY' | sed 's/^/    D-2 universal-tenant \/ company-identity statements: /'
git -C $IRR show refs/heads/main:evidence/integration/convergence/2026-10-07/P3-persistence-durability.md | grep -c 'AG-5 company-level IRR↔IPD mapping' | sed 's/^/V6 P3 AG-5 row lines: /'
echo "== V7 G24 presence (branch vs IPD main) =="
for c in refs/heads/arena/01a0e6d9-iips-production-market-data refs/heads/main; do git -C $IPD cat-file -e $c:src/app_identity/service.ts 2>/dev/null && echo "V7 src/app_identity/service.ts present at $c ($(git -C $IPD rev-parse $c | cut -c1-12))" || echo "V7 src/app_identity/service.ts ABSENT at $c"; done
echo "== V8 csipCompanyId UUID presence =="
ir=0; for t in $(git -C $IRR for-each-ref --format='%(objectname)' refs/heads refs/pull refs/tags | while read c; do git -C $IRR rev-parse "$c^{tree}" 2>/dev/null; done | sort -u); do n=$(git -C $IRR grep -l '5233149d-2a2d-4644-a6a7-e1ed5e133285' $t 2>/dev/null | wc -l); ir=$((ir+n)); done; echo "V8a IRR trees containing csipCompanyId UUID: $ir"
ip=$(git -C $IPD grep -l '5233149d-2a2d-4644-a6a7-e1ed5e133285' refs/heads/arena/01a0ae80-iips-production-market-data 2>/dev/null | wc -l); echo "V8b IPD arena/01a0ae80 files containing UUID: $ip"
echo "== V9 D115 release-authority state on arena/01a0ae80 =="
git -C $IPD show refs/heads/arena/01a0ae80-iips-production-market-data:d115/governance/identity-mapping/released-state/hdfc-life-idmap-d115-group2-1.0.0.release-authority.json | grep -E '"(mappingReleased|mappingActivated|mappingRegistered|mappingLoaded|productionEligible|releaseAuthorization)"' | sed 's/^ */V9 /' || true
git -C $IPD show refs/heads/arena/01a0ae80-iips-production-market-data:d115/governance/identity-mapping/released-state/hdfc-life-idmap-d115-group2-1.0.0.release-authority.json | grep -E 'mappingReleased|releaseAuthorization|mappingActivated' | head -3 >/dev/null
echo "== V10 NP-06 governance docs on IRR main (correction C1 check) =="
for p in docs/integration/IIPS_v3.0_NP06_REPORTS_GOVERNANCE_DECISIONS.md docs/v3.0/g3-build/PROGRAM_v3.0_NP06_REPORTS_FINAL_QUALIFICATION.md; do git -C $IRR cat-file -e refs/heads/main:$p 2>/dev/null && echo "V10 PRESENT on main: $p" || echo "V10 absent on main: $p"; done
echo "== V11-V13 IRR route and branch facts =="
git -C $IRR show refs/heads/main:frontend/src/app/App.tsx | grep -n "research/sector/:id\|intelligence/\*\|evidence/snapshots\|evidence/replay\"" | sed 's/^/V11 main App.tsx: /'
git -C $IRR cat-file -e refs/heads/phase13-next:frontend/src/features/intelligence/IntelligenceOpportunities.tsx && echo "V12 phase13-next IntelligenceOpportunities.tsx present"; git -C $IRR cat-file -e refs/heads/main:frontend/src/features/intelligence/IntelligenceOpportunities.tsx 2>/dev/null && echo "V12 (unexpected) present on main" || echo "V12 IntelligenceOpportunities.tsx absent on main"
for b in arena/01a0ddea-iips-review-recovered arena/01a0e30f-iips-review-recovered; do git -C $IRR cat-file -e refs/heads/$b:governance/iips/AUTH-NP-18-INTELLIGENCE-EXPOSURE-IMPLEMENTATION-AUTHORITY-2026-09-26.md && echo "V13 AUTH-NP-18 present on $b"; done; git -C $IRR cat-file -e refs/heads/main:governance/iips/AUTH-NP-18-INTELLIGENCE-EXPOSURE-IMPLEMENTATION-AUTHORITY-2026-09-26.md 2>/dev/null && echo "V13 (unexpected) on main" || echo "V13 AUTH-NP-18 absent on main"
echo "== V14 IPD main has no D107 record =="; git -C $IPD cat-file -e refs/heads/main:docs/D107_EOD_PRODUCTION_READINESS_GATE_ADJUDICATION.md 2>/dev/null && echo "V14 (unexpected) D107 on main" || echo "V14 D107 record absent on IPD main"; git -C $IPD cat-file -e refs/heads/arena/01a0a438-iips-production-market-data:docs/D107_EOD_PRODUCTION_READINESS_GATE_ADJUDICATION.md && echo "V14 D107 record present on arena/01a0a438"
echo "== V15 Phase 14.1 archive contains WorkflowView =="; git -C $IRR show refs/heads/phase14.1-recovery-deposit:artifacts/phase14.1-recovery-snapshot/v3.0-phase14.1-certified-snapshot.tar.gz | tar -tzf - 2>/dev/null | grep -c 'features/workflow/WorkflowView.tsx' | sed 's/^/V15 WorkflowView entries in archive: /'
echo "== V16 reports-transport on IRR branch vs main =="; git -C $IRR cat-file -e refs/heads/arena/01a0f1b3-iips-review-recovered:frontend/server/reports-transport.ts && echo "V16 reports-transport.ts present on arena/01a0f1b3"; git -C $IRR cat-file -e refs/heads/main:frontend/server/reports-transport.ts 2>/dev/null && echo "V16 (unexpected) on main" || echo "V16 reports-transport.ts absent on main"
echo "== V17 IPD tags carry PortfolioIntelligence =="; for t in portfolio-option-a-cb969b6 post-cleanup-baseline-b46b4f4; do git -C $IPD cat-file -e refs/tags/$t:iips-platform/src/sector-engines/cross-sector/portfolio/PortfolioIntelligence.ts 2>/dev/null && echo "V17 present at tag $t" || echo "V17 absent at tag $t"; done
echo "== V18 IPD main UI01 view model and registry =="; git -C $IPD cat-file -e refs/heads/main:src/ui/view_models/ui01_replay_studio.ts && echo "V18 ui01_replay_studio.ts present on IPD main"; git -C $IPD show refs/heads/main:src/ui/ui_registry.ts | grep -c "UI01_REPLAY_STUDIO" | sed 's/^/V18 UI01_REPLAY_STUDIO lines in registry: /'
echo "== V19 IPD pit_read_service AG-5 comment on arena/01a0e6d9 =="; git -C $IPD show refs/heads/arena/01a0e6d9-iips-production-market-data:src/pit/pit_read_service.ts | grep -n "AG-5" | sed 's/^/V19 /' | cut -c1-200
echo "== V20 P5 row 12 text and location =="; git -C $IRR show refs/heads/main:evidence/integration/convergence/2026-10-07/P5-capability-sweep.md | grep -n "^| 12 |" | cut -c1-160 | sed 's/^/V20 /'
echo "== V21 P5 'global search command palette' location =="; git -C $IRR show refs/heads/main:evidence/integration/convergence/2026-10-07/P5-capability-sweep.md | grep -n "global search command palette\|^## " | cut -c1-140 | sed 's/^/V21 /'
